// src/app/app.component.ts
import { Component, OnInit, OnDestroy, inject, signal } from '@angular/core';
import { BibleService, BibleVerse } from './services/bible.service';
import { WeatherService, WeatherData, WeatherError } from './services/weather.service';
import { CuteMessageService } from './services/cute-message.service';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit, OnDestroy {
  private bibleService = inject(BibleService);
  private weatherService = inject(WeatherService);
  private cuteMessageService = inject(CuteMessageService);

  bibleVerse = signal<BibleVerse | null>(null);
  bibleLoading = signal(true);
  bibleError = signal(false);

  weather = signal<WeatherData | null>(null);
  weatherLoading = signal(true);
  weatherError = signal<WeatherError | null>(null);

  cuteMessage = signal('');

  showIntro = signal(true);
  musicPlaying = signal(false);
  greetingText = signal('');
  greetingEmoji = signal('');

  private midnightTimer: ReturnType<typeof setTimeout> | null = null;
  private musicTimer: ReturnType<typeof setTimeout> | null = null;
  private audio: HTMLAudioElement | null = null;

  dismissIntro(): void {
    this.showIntro.set(false);
    if (!this.audio) return;
    this.audio.play().then(() => this.musicPlaying.set(true)).catch(() => {});
  }

  toggleMusic(): void {
    if (!this.audio) return;
    if (this.musicPlaying()) {
      this.audio.pause();
      this.musicPlaying.set(false);
    } else {
      this.audio.play().then(() => this.musicPlaying.set(true)).catch(() => {});
    }
  }

  private setGreeting(): void {
    const hour = new Date().getHours();
    if (hour >= 5 && hour < 12)  { this.greetingText.set('Good Morning');            this.greetingEmoji.set('☀️'); }
    else if (hour >= 12 && hour < 17) { this.greetingText.set('Good Afternoon');     this.greetingEmoji.set('🌸'); }
    else if (hour >= 17 && hour < 21) { this.greetingText.set('Good Evening');       this.greetingEmoji.set('🌅'); }
    else                              { this.greetingText.set('Goodnight mi chula reina'); this.greetingEmoji.set('🌙'); }
  }

  ngOnInit(): void {
    this.setGreeting();
    this.audio = new Audio('assets/music.mp3');
    this.audio.loop = true;
    this.audio.volume = 0.5;
    this.cuteMessage.set(this.cuteMessageService.getMessage());
    this.scheduleMidnightRefresh();
    this.loadBibleVerse();
    this.loadWeather();
  }

  ngOnDestroy(): void {
    if (this.midnightTimer !== null) clearTimeout(this.midnightTimer);
    if (this.musicTimer !== null) clearTimeout(this.musicTimer);
    this.audio?.pause();
  }

  private scheduleMidnightRefresh(): void {
    this.midnightTimer = setTimeout(() => {
      this.cuteMessage.set(this.cuteMessageService.getMessage());
      this.loadBibleVerse();
      this.scheduleMidnightRefresh();
    }, this.cuteMessageService.msUntilMidnight());
  }

  loadBibleVerse(): void {
    this.bibleLoading.set(true);
    this.bibleError.set(false);
    this.bibleService.getDailyVerse().subscribe({
      next: (verse) => {
        this.bibleVerse.set(verse);
        this.bibleLoading.set(false);
      },
      error: () => {
        this.bibleError.set(true);
        this.bibleLoading.set(false);
      }
    });
  }

  loadWeather(): void {
    this.weatherLoading.set(true);
    this.weatherError.set(null);
    this.weatherService.getWeather().subscribe({
      next: (data) => {
        this.weather.set(data);
        this.weatherLoading.set(false);
      },
      error: (err: { type: WeatherError }) => {
        this.weatherError.set(err?.type ?? 'api');
        this.weatherLoading.set(false);
      }
    });
  }

}


@if (showIntro()) {
  <div class="intro-overlay" (click)="dismissIntro()">
    <div class="intro-box">
      <p class="intro-greeting">{{ greetingText() }} <span class="emoji">{{ greetingEmoji() }}</span></p>
      <p class="intro-title">MeliBoo</p>
      <p class="intro-hint">tap to open ✦</p>
    </div>
  </div>
}

@if (!showIntro()) {
  <button class="music-btn" (click)="toggleMusic()" [title]="musicPlaying() ? 'Pause music' : 'Play music'">
    {{ musicPlaying() ? '♪' : '♩' }}
  </button>
}

<div class="flowers" aria-hidden="true">
  <span class="flower f1"></span>
  <span class="flower f2"></span>
  <span class="flower f3"></span>
  <span class="flower f4"></span>
  <span class="flower f5"></span>
  <span class="flower f6"></span>
</div>

<div class="page">

  <header class="header">
    <h1 class="title">MeliBoo</h1>
    <p class="subtitle">just for you</p>
  </header>

  <main class="cards">

    <!-- Bible Quote -->
    <article class="card bible-card">
      <span class="card-glyph">✦</span>
      <h2 class="card-label">Today's Word</h2>

      @if (bibleLoading()) {
        <div class="skeleton">
          <div class="skeleton-line"></div>
          <div class="skeleton-line"></div>
          <div class="skeleton-line short"></div>
        </div>
      } @else if (bibleError()) {
        <p class="error-text">Could not load verse</p>
        <button class="retry" (click)="loadBibleVerse()">Try again</button>
      } @else {
        <blockquote class="verse">
          <p class="verse-text">{{ bibleVerse()?.text }}</p>
          <cite class="verse-ref">{{ bibleVerse()?.reference }}</cite>
        </blockquote>
      }
    </article>

    <!-- Weather -->
    <article class="card weather-card">
      <span class="card-glyph">☁</span>
      <h2 class="card-label">Right Now</h2>

      @if (weatherLoading()) {
        <div class="skeleton">
          <div class="skeleton-line short center"></div>
          <div class="skeleton-line short center"></div>
          <div class="skeleton-line shorter center"></div>
        </div>
      } @else if (weatherError()) {
        @if (weatherError() === 'location') {
          <p class="error-text">Location access was denied.<br>Allow it in your browser and retry.</p>
        } @else {
          <p class="error-text">Weather API error.<br>Check your API key in environment.ts.</p>
        }
        <button class="retry" (click)="loadWeather()">Try again</button>
      } @else {
        <div class="weather-body">
          <img class="weather-icon" [src]="weather()!.icon" [alt]="weather()!.description" />
          <div class="temp">{{ weather()!.temperature }}<span class="deg">°C</span></div>
          <div class="city">{{ weather()!.city }}</div>
          <div class="desc">{{ weather()!.description }}</div>
          <div class="feels">feels like {{ weather()!.feelsLike }}°C</div>
        </div>
      }
    </article>

    <!-- Cute Message -->
    <article class="card message-card">
      <span class="card-glyph">♡</span>
      <h2 class="card-label">A Little Note</h2>
      <p class="message-text">{{ cuteMessage() }}</p>
    </article>

  </main>

  <footer class="footer">
    <p>Made for you by Ra(h)ul </p>
  </footer>

</div>

// app/page.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import styles from './page.module.scss';
import { getMessage, msUntilMidnight } from '@/lib/messages';
import { getDailyVerse, BibleVerse } from '@/lib/bible';
import { getWeather, WeatherData, WeatherError } from '@/lib/weather';

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

function getGreeting(): { text: string; emoji: string } {
  const hour = new Date().getHours();
  if (hour >= 5 && hour < 12)  return { text: 'Good Morning',             emoji: '☀️' };
  if (hour >= 12 && hour < 17) return { text: 'Good Afternoon',           emoji: '🌸' };
  if (hour >= 17 && hour < 21) return { text: 'Good Evening',             emoji: '🌅' };
  return                               { text: 'Goodnight mi chula reina', emoji: '🌙' };
}

export default function Home() {
  const [showIntro, setShowIntro]         = useState(true);
  const [musicPlaying, setMusicPlaying]   = useState(false);
  const [greeting]                        = useState(getGreeting);

  const [bibleVerse, setBibleVerse]       = useState<BibleVerse | null>(null);
  const [bibleLoading, setBibleLoading]   = useState(true);
  const [bibleError, setBibleError]       = useState(false);

  const [weather, setWeather]             = useState<WeatherData | null>(null);
  const [weatherLoading, setWeatherLoading] = useState(true);
  const [weatherError, setWeatherError]   = useState<WeatherError | null>(null);

  const [cuteMessage, setCuteMessage]     = useState('');

  const audioRef = useRef<HTMLAudioElement | null>(null);

  useEffect(() => {
    audioRef.current = new Audio(`${BASE}/assets/music.mp3`);
    audioRef.current.loop = true;
    audioRef.current.volume = 0.5;
    return () => { audioRef.current?.pause(); };
  }, []);

  useEffect(() => {
    setCuteMessage(getMessage());
    loadBibleVerse();
    loadWeather();

    const timer = setTimeout(() => {
      setCuteMessage(getMessage());
      loadBibleVerse();
    }, msUntilMidnight());
    return () => clearTimeout(timer);
  }, []);

  function loadBibleVerse() {
    setBibleLoading(true);
    setBibleError(false);
    getDailyVerse()
      .then((v) => { setBibleVerse(v); setBibleLoading(false); })
      .catch(() => { setBibleError(true); setBibleLoading(false); });
  }

  function loadWeather() {
    setWeatherLoading(true);
    setWeatherError(null);
    getWeather()
      .then((d) => { setWeather(d); setWeatherLoading(false); })
      .catch((err: { type: WeatherError }) => {
        setWeatherError(err?.type ?? 'api');
        setWeatherLoading(false);
      });
  }

  function dismissIntro() {
    setShowIntro(false);
    audioRef.current?.play().then(() => setMusicPlaying(true)).catch(() => {});
  }

  function toggleMusic() {
    if (!audioRef.current) return;
    if (musicPlaying) {
      audioRef.current.pause();
      setMusicPlaying(false);
    } else {
      audioRef.current.play().then(() => setMusicPlaying(true)).catch(() => {});
    }
  }

  const flowerStyle = { backgroundImage: `url('${BASE}/assets/sunflower.png')` };

  return (
    <>
      {showIntro && (
        <div className={styles.introOverlay} onClick={dismissIntro}>
          <div className={styles.introBox}>
            <p className={styles.introGreeting}>
              {greeting.text} <span className={styles.emoji}>{greeting.emoji}</span>
            </p>
            <p className={styles.introTitle}>MeliBoo</p>
            <p className={styles.introHint}>tap to open ✦</p>
          </div>
        </div>
      )}

      {!showIntro && (
        <button
          className={styles.musicBtn}
          onClick={toggleMusic}
          title={musicPlaying ? 'Pause music' : 'Play music'}
        >
          {musicPlaying ? '♪' : '♩'}
        </button>
      )}

      <div className={styles.flowers} aria-hidden="true">
        {[1, 2, 3, 4, 5, 6].map((i) => (
          <span key={i} className={`${styles.flower} ${styles[`f${i}`]}`} style={flowerStyle} />
        ))}
      </div>

      <div className={styles.page}>
        <header className={styles.header}>
          <h1 className={styles.title}>MeliBoo</h1>
          <p className={styles.subtitle}>just for you</p>
        </header>

        <main className={styles.cards}>

          {/* Bible */}
          <article className={`${styles.card} ${styles.bibleCard}`}>
            <span className={styles.cardGlyph}>✦</span>
            <h2 className={styles.cardLabel}>Today's Word</h2>
            {bibleLoading ? (
              <div className={styles.skeleton}>
                <div className={styles.skeletonLine} />
                <div className={styles.skeletonLine} />
                <div className={`${styles.skeletonLine} ${styles.short}`} />
              </div>
            ) : bibleError ? (
              <>
                <p className={styles.errorText}>Could not load verse</p>
                <button className={styles.retry} onClick={loadBibleVerse}>Try again</button>
              </>
            ) : (
              <blockquote className={styles.verse}>
                <p className={styles.verseText}>{bibleVerse?.text}</p>
                <cite className={styles.verseRef}>{bibleVerse?.reference}</cite>
              </blockquote>
            )}
          </article>

          {/* Weather */}
          <article className={`${styles.card} ${styles.weatherCard}`}>
            <span className={styles.cardGlyph}>☁</span>
            <h2 className={styles.cardLabel}>Right Now</h2>
            {weatherLoading ? (
              <div className={styles.skeleton}>
                <div className={`${styles.skeletonLine} ${styles.short} ${styles.center}`} />
                <div className={`${styles.skeletonLine} ${styles.short} ${styles.center}`} />
                <div className={`${styles.skeletonLine} ${styles.shorter} ${styles.center}`} />
              </div>
            ) : weatherError ? (
              <>
                <p className={styles.errorText}>
                  {weatherError === 'location'
                    ? <>Location access was denied.<br />Allow it in your browser and retry.</>
                    : <>Weather API error.<br />Check your API key.</>
                  }
                </p>
                <button className={styles.retry} onClick={loadWeather}>Try again</button>
              </>
            ) : (
              <div className={styles.weatherBody}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img className={styles.weatherIcon} src={weather!.icon} alt={weather!.description} />
                <div className={styles.temp}>
                  {weather!.temperature}<span className={styles.deg}>°C</span>
                </div>
                <div className={styles.city}>{weather!.city}</div>
                <div className={styles.desc}>{weather!.description}</div>
                <div className={styles.feels}>feels like {weather!.feelsLike}°C</div>
              </div>
            )}
          </article>

          {/* Cute Message */}
          <article className={`${styles.card} ${styles.messageCard}`}>
            <span className={styles.cardGlyph}>♡</span>
            <h2 className={styles.cardLabel}>A Little Note</h2>
            <p className={styles.messageText}>{cuteMessage}</p>
          </article>

        </main>

        <footer className={styles.footer}>
          <p>Made for you by Ra(h)ul</p>
        </footer>
      </div>
    </>
  );
}
